# CS549-02 Machine Learning: Irfan Khan
# Assignment 1: Python and numpy basics


**Total: 10 points**

In this assignment, you will gain practice in the use of Jupyter platform, write python code and utilize the numpy package.

There are five cells below. Please add missing code in each cell and run the cells from top to bottom.

Your output should be the same as the expected output.

References: Python: https://docs.python.org/3/; numpy: https://numpy.org/doc/stable/

## 1 (2 points): String Manipulation:

Given a string, write a Python function to:

1. Calculate the length of the string.
2. Print the string in uppercase.
3. Count the number of vowels in the string.
4. Check if the string is a palindrome.

In [ ]:
def string_operations(input_string):
    # Calculate length
    length = len(input_string)

    # End your code


    # Print in uppercase
    #Begin your code
    uppercase_string = input_string.upper()

    #End your code

    # Count vowels
    #Begin your Code
    vowels = sum(1 for char in input_string.lower() if char in 'aeiou')

    #End your code

    # Check palindrome
    #Begin your code
    is_palindrome = input_string ==input_string[::-1]

    #End your code

    return length, uppercase_string, vowels, is_palindrome

# Example usage:
input_str = "python"
result = string_operations(input_str)
print("Length:", result[0])
print("Uppercase String:", result[1])
print("Number of Vowels:", result[2])
print("Is Palindrome:", result[3])
input_str = "rotator"
result = string_operations (input_str)
print("Length:", result[0])
print("Uppercase String:", result[1])
print("Number of Vowels:", result[2])
print("Is Palindrome:", result[3])

Length: 6
Uppercase String: PYTHON
Number of Vowels: 1
Is Palindrome: False
Length: 7
Uppercase String: ROTATOR
Number of Vowels: 3
Is Palindrome: True


### Expected Output

Length: 6 <br>
Uppercase String: PYTHON <br>
Number of Vowels: 1 <br>
Is Palindrome: False <br>
Length: 7 <br>
Uppercase String: ROTATOR <br>
Number of Vowels: 3 <br>
Is Palindrome: True

## 2 (2 points) : List Operations

Given a list of integers, write a Python function to:

1. Calculate the sum of the list.
2. Find the maximum and minimum values in the list.
3. Create a new list containing only the even numbers from the original list.

In [ ]:
def list_operations(numbers):
    # Calculate sum

    # Begin your code
    list_sum = sum(numbers)


    # End your code

    # Find max and min

    # Begin your code
    max_value = max(numbers)
    min_value = min(numbers)

    #End your code

    # Extract even numbers

    #Begin your code
    even_numbers = [num for num in numbers if num % 2 == 0]


    return list_sum, max_value, min_value, even_numbers
    #End your code

# Example usage:
numbers_list = [1, 4, 7, 2, 9, 10, 6]
result = list_operations(numbers_list)
print("Sum:", result[0])
print("Max Value:", result[1])
print("Min Value:", result[2])
print("Even Numbers:", result[3])

Sum: 39
Max Value: 10
Min Value: 1
Even Numbers: [4, 2, 10, 6]


### Expected Output

Sum: 39<br>
Max Value: 10<br>
Min Value: 1<br>
Even Numbers: [4, 2, 10, 6]

## NumPy use

First import numpy

In [ ]:
import numpy as np


## 3 (2 points): Matrix Operations

Create two matrices (3x3) and perform the following operations:

Matrix addition.<br>
Matrix multiplication.<br>
Element-wise multiplication.<br>
Transpose of the second matrix.<br>

In [ ]:
# Creating matrices
#For consistency in assignment results, please don't change the below two matrices

matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Operations

# Matrix addition

matrix_addition = matrix1 + matrix2

# Matrix Multiplication

matrix_multiplication = np.dot(matrix1, matrix2)

#end code#

# Element-wise Multiplication

elementwise_multiplication = matrix1 * matrix2

#end code

#Transpose of Matrix 2
transposed_matrix2 = np.transpose(matrix2)

#end code

print("Matrix Addition:")
print(matrix_addition)

print("\nMatrix Multiplication:")
print(matrix_multiplication)

print("\nElement-wise Multiplication:")
print(elementwise_multiplication)

print("\nTransposed Matrix2:")
print(transposed_matrix2)

Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Transposed Matrix2:
[[9 6 3]
 [8 5 2]
 [7 4 1]]


### Expected output

Matrix Addition:<br>
[[10 10 10]<br>
 [10 10 10]<br>
 [10 10 10]]<br>

Matrix Multiplication:<br>
[[ 30  24  18]<br>
 [ 84  69  54]<br>
 [138 114  90]]<br>

Element-wise Multiplication:<br>
[[ 9 16 21]<br>
 [24 25 24]<br>
 [21 16  9]]<br>

Transposed Matrix2:<br>
[[9 6 3]<br>
 [8 5 2]<br>
 [7 4 1]]<br>


## 4 (2 points): Data Analysis with NumPy

Load the given dataset A1Data (you can use numpy.loadtxt or any other suitable method) and perform the following:

Calculate the mean and standard deviation of each column.<br>
Find the row with the maximum sum.<br>
Normalize the dataset by subtracting the mean and dividing by the standard deviation for each column.

In [ ]:
from google.colab import files
uploaded = files.upload()
# Load dataset
data = np.loadtxt('A1data.txt')

# Operations.
#Get column means in "column_means",
column_means = np.mean(data, axis=0)

#column std deviation in "column_stds",
column_stds = np.std(data, axis=0, ddof=0)

#row with max sum in "max_sum_row"
max_sum_row = np.argmax(np.sum(data, axis=1))

# normalized data =(data-column_means)/column_stds in

normalized_data = (data-column_means)/column_stds

#begin your code


#end your code
print ("data:", data)

print("Column Means:")
print(column_means)

print("\nColumn Standard Deviations:")
print(column_stds)

print("\nRow with Maximum Sum:")
print(data[max_sum_row])

print("\nNormalized Data:")
print(normalized_data)

Saving A1data.txt to A1data.txt
data: [[ 4.  5.  6.]
 [ 3.  6.  8.]
 [10.  3.  5.]
 [11. 23.  7.]
 [ 2. 45.  8.]
 [ 1.  5.  9.]]
Column Means:
[ 5.16666667 14.5         7.16666667]

Column Standard Deviations:
[ 3.89087251 15.20690633  1.34370962]

Row with Maximum Sum:
[ 2. 45.  8.]

Normalized Data:
[[-0.29984706 -0.62471615 -0.86824314]
 [-0.55685882 -0.55895656  0.62017367]
 [ 1.24222352 -0.75623534 -1.61245155]
 [ 1.49923528  0.55895656 -0.12403473]
 [-0.81387058  2.00566765  0.62017367]
 [-1.07088234 -0.62471615  1.36438208]]


## Expected Result

data: [[ 4.  5.  6.]<br>
 [ 3.  6.  8.]<br>
 [10.  3.  5.]<br>
 [11. 23.  7.]<br>
 [ 2. 45.  8.]<br>
 [ 1.  5.  9.]]<br>
Column Means:<br>
[ 5.16666667 14.5         7.16666667]<br>

Column Standard Deviations:<br>
[ 3.89087251 15.20690633  1.34370962]<br>

Row with Maximum Sum:<br>
[ 2. 45.  8.]<br>

Normalized Data:
[[-0.29984706 -0.62471615 -0.86824314]<br>
 [-0.55685882 -0.55895656  0.62017367]<br>
 [ 1.24222352 -0.75623534 -1.61245155]<br>
 [ 1.49923528  0.55895656 -0.12403473]<br>
 [-0.81387058  2.00566765  0.62017367]<br>
 [-1.07088234 -0.62471615  1.36438208]]

## 5 (2 points): Basic linear algebra in numpy
**2 points**
Use numpy linalg to solve simultaneous linear equations in 3 variables (x1,x2,x3)



In [ ]:

#Equation 1: -2 x1 - x3 = 1
#Equation 2: -2 x2 - x3 = 1
#Equation 3: 3 x1 + 3 x2 + x3 = 1

#Start your code
A = np.array([[-2, 0, -1],
            [0,-2,-1],
             [3, 3, 1]])

b = np.array([1, 1, 1])


#Return the solution to x1,x2,x3 in variable "solution"
solution = np.linalg.solve(A, b)

#end your code

print('x1 = ', solution[0])
print('x2 = ', solution[1])
print('x3 = ', solution[2])

x1 =  0.5000000000000001
x2 =  0.4999999999999999
x3 =  -1.9999999999999998


## Expected Output:
x1 = 0.5<br>
x2 = 0.5<br>
x3 = -2.0